name: Compile
description: Compile Chromium
inputs:
  architecture:
    required: true
    type: string
runs:
  using: composite
  steps:
    - run: git apply "${GITHUB_WORKSPACE}/assets/patches/source/fix-disable-speech-service.patch"
      shell: bash
      working-directory: ${{ github.workspace }}/chromium
    - name: Create output dir
      shell: bash
      run: mkdir out/Default
      working-directory: ${{ github.workspace }}/chromium
    - name: Configure the build
      shell: bash
      run: cp "${GITHUB_WORKSPACE}/assets/args.gn" out/Default/args.gn
      working-directory: ${{ github.workspace }}/chromium
    - name: Set up the build
      run: gn gen out/Default
      shell: bash
      working-directory: ${{ github.workspace }}/chromium
    - name: Build headless_shell
      run: autoninja -C out/Default headless_shell chrome
      shell: bash
      working-directory: ${{ github.workspace }}/chromium